TEMPLATE = app
DESTDIR = dist/Debug/GNU-Linux-x86
TARGET = TakeYourPillsVideoEncoder
VERSION = 1.0.0
CONFIG -= debug_and_release app_bundle lib_bundle
CONFIG += debug 
QT = core gui
SOURCES += form.cpp tinystr.cpp tinyxmlparser.cpp tinyxmlerror.cpp tinyxml.cpp main.cpp
HEADERS += tinystr.h tinyxml.h commands.h form.h
FORMS +=
RESOURCES +=
TRANSLATIONS +=
OBJECTS_DIR = build/Debug/GNU-Linux-x86
MOC_DIR = 
RCC_DIR = 
UI_DIR = 
QMAKE_CC = gcc
QMAKE_CXX = g++
DEFINES += 
INCLUDEPATH += 
LIBS += 
